/* Demo-only client component for cleaning AI text on-page. */
"use client";

import { useState } from "react";

function countWords(text: string): number {
  const trimmed = text.trim();
  if (!trimmed) return 0;
  return trimmed.split(/\s+/).length;
}

function countHiddenMarkers(text: string): number {
  // Simple placeholder logic for watermark-like phrases.
  const patterns = [/watermark/gi, /ai generated/gi, /generated by/gi, /source:/gi];

  return patterns.reduce((total, pattern) => {
    const matches = text.match(pattern);
    return total + (matches ? matches.length : 0);
  }, 0);
}

function cleanText(text: string): string {
  let result = text;
  // Collapse runs of whitespace into single spaces.
  result = result.replace(/\s+/g, " ");
  // Restore paragraph breaks where there were two or more newlines.
  result = result.replace(/(\n\s*){2,}/g, "\n\n");
  return result.trim();
}

export default function CleanTextDemo() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);

  const words = countWords(input);
  const hidden = countHiddenMarkers(input);

  const handleClean = () => {
    const cleaned = cleanText(input);
    setOutput(cleaned);
    setCopied(false);
  };

  const handleClear = () => {
    setInput("");
    setOutput("");
    setCopied(false);
  };

  const handleCopy = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  return (
    <section className="space-y-4 rounded-3xl border border-zinc-800 bg-zinc-900/70 p-5 text-sm text-zinc-100">
      <header className="flex flex-wrap items-center justify-between gap-3 text-xs text-zinc-400">
        <div className="font-medium text-zinc-200">Try a cleanup tool preview</div>
        <div className="flex items-center gap-3">
          <span className="rounded-full bg-zinc-800 px-2 py-1 text-[11px]">
            {words} words
          </span>
          <span className="rounded-full bg-zinc-800 px-2 py-1 text-[11px]">
            {hidden} hidden
          </span>
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <label className="text-xs font-medium text-zinc-300">
            Paste your messy AI text
          </label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Paste text from ChatGPT, Gemini, Claude..."
            className="h-40 w-full resize-none rounded-2xl border border-zinc-800 bg-zinc-950/70 p-3 text-xs text-zinc-100 outline-none focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400/60"
          />
        </div>
        <div className="space-y-2">
          <label className="text-xs font-medium text-zinc-300">
            Clean result
          </label>
          <textarea
            value={output}
            readOnly
            placeholder="Your cleaned text will appear here."
            className="h-40 w-full resize-none rounded-2xl border border-zinc-800 bg-zinc-950/40 p-3 text-xs text-zinc-100/80 outline-none"
          />
        </div>
      </div>

      <div className="flex flex-wrap gap-3 pt-1 text-xs">
        <button
          type="button"
          onClick={handleClean}
          className="inline-flex items-center justify-center rounded-full bg-indigo-500 px-4 py-2 font-medium text-white shadow-sm shadow-indigo-500/40 hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-60"
          disabled={!input.trim()}
        >
          Clean Text
        </button>
        <button
          type="button"
          onClick={handleClear}
          className="inline-flex items-center justify-center rounded-full border border-zinc-700 px-4 py-2 font-medium text-zinc-100 hover:border-zinc-500 hover:bg-zinc-900"
          disabled={!input && !output}
        >
          Clear
        </button>
        <button
          type="button"
          onClick={handleCopy}
          className="inline-flex items-center justify-center rounded-full border border-zinc-700 px-4 py-2 font-medium text-zinc-100 hover:border-zinc-500 hover:bg-zinc-900 disabled:cursor-not-allowed disabled:opacity-60"
          disabled={!output}
        >
          {copied ? "Copied" : "Copy output"}
        </button>
      </div>
    </section>
  );
}

