import type { MetadataRoute } from "next";

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://chatgpt4mobile.com";

const BLOG_SLUGS = [
  "how-to-use-chatgpt-on-mobile",
  "chatgpt-mobile-app-tips",
  "best-chatgpt-prompts-for-mobile-users",
  "chatgpt-on-iphone-tips-and-tricks",
  "chatgpt-android-app-guide",
  "how-to-copy-chatgpt-text-on-mobile",
  "chatgpt-mobile-formatting-issues",
  "chatgpt-on-ipad-tips",
  "how-to-use-chatgpt-offline-mobile",
  "chatgpt-mobile-vs-desktop-differences",
  "chatgpt-mobile-shortcuts",
  "how-to-share-chatgpt-responses-mobile",
  "chatgpt-voice-mode-mobile-guide",
  "chatgpt-mobile-productivity-tips",
  "how-to-save-chatgpt-conversations-mobile",
  "chatgpt-mobile-data-usage-tips",
  "best-chatgpt-mobile-workflows",
  "chatgpt-mobile-notifications-setup",
  "how-to-use-chatgpt-for-notes-on-mobile",
  "chatgpt-mobile-app-review-2026",
  "how-to-clean-chatgpt-text",
  "clean-chatgpt-text-before-publishing",
  "remove-hidden-characters-chatgpt",
  "chatgpt-text-cleaner-free",
  "how-to-fix-chatgpt-copy-paste-issues",
  "chatgpt-text-formatting-problems-solved",
  "clean-chatgpt-output-for-wordpress",
  "how-to-clean-chatgpt-text-for-email",
  "remove-chatgpt-watermarks-from-text",
  "chatgpt-text-cleaning-workflow",
  "best-way-to-clean-chatgpt-responses",
  "clean-chatgpt-text-for-google-docs",
  "how-to-normalize-chatgpt-text",
  "chatgpt-invisible-characters-explained",
  "clean-chatgpt-text-for-cms-publishing",
  "how-to-remove-unicode-from-chatgpt",
  "chatgpt-text-artifacts-explained",
  "clean-chatgpt-text-for-social-media",
  "how-to-fix-chatgpt-spacing-issues",
  "chatgpt-text-cleaning-best-practices",
  "fix-chatgpt-formatting-in-word",
  "chatgpt-formatting-issues-explained",
  "remove-chatgpt-line-breaks",
  "fix-chatgpt-spacing-problems",
  "chatgpt-em-dash-removal-guide",
  "chatgpt-bold-text-removal",
  "fix-chatgpt-markdown-formatting",
  "chatgpt-formatting-for-emails",
  "remove-chatgpt-bullet-points",
  "fix-chatgpt-paragraph-spacing",
  "chatgpt-formatting-for-wordpress",
  "chatgpt-text-normalization-guide",
  "fix-chatgpt-formatting-in-google-docs",
  "chatgpt-special-characters-removal",
  "chatgpt-formatting-fixer-tools",
  "best-ai-text-cleaning-tools-2026",
  "ai-text-formatter-tools-review",
  "free-ai-text-cleaners-comparison",
  "ai-watermark-remover-tools",
  "best-tools-to-fix-ai-formatting",
  "ai-text-normalization-tools",
  "remove-ai-formatting-artifacts",
  "ai-copy-paste-cleaner-tools",
  "best-ai-text-editors-2026",
  "ai-text-cleanup-workflow",
  "tools-to-fix-ai-generated-text",
  "ai-text-sanitizer-tools-review",
  "remove-invisible-characters-ai-text",
  "best-free-ai-writing-cleanup-tools",
  "ai-text-formatting-best-practices",
  "best-productivity-apps-for-mobile-2026",
  "ai-tools-for-mobile-content-creators",
  "mobile-workflow-for-content-creators",
  "best-mobile-apps-for-bloggers-2026",
  "ai-writing-tools-for-mobile-users",
  "mobile-content-creation-workflow",
  "best-note-taking-apps-mobile-2026",
  "mobile-tools-for-social-media-managers",
  "ai-productivity-tools-for-iphone",
  "best-mobile-tools-for-remote-workers",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${BASE_URL}/guides`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/guides/clean-chatgpt-text`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/guides/mobile-copy-paste-issues`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/guides/how-to-clean-chatgpt-text-on-android`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/guides/chatgpt-watermark-remover-mobile`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/guides/chatgpt-text-cleaner-iphone`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/best-chatgpt-cleanup-tools`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
  ];

  const blogRoutes: MetadataRoute.Sitemap = BLOG_SLUGS.map((slug) => ({
    url: `${BASE_URL}/blog/${slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [...staticRoutes, ...blogRoutes];
}
